#!/usr/bin/env bash
set -o errtrace -o nounset -o pipefail

source potpourri.shlib.panic.__err_exit_trap__.bash
source potpourri.shlib.panic.bash

# shellcheck disable=SC2034
declare -r DOCOPT_PROGRAM_VERSION="0.0.1
Release date: 16 June 2020"
# shellcheck disable=SC2034
declare -r DOC='Usage:
  makeall [<args>...]
  makeall --version
  makeall -h | --help

Options:
  --version  Show version.
  -h --help  Show this screen.

Author: Nikita Belyakov "Potpourri"
License: MIT
Repo: https://github.com/Potpourri/Hyperborea/tree/master/makeall'

main() {
	local -i exitCode=0
	local project
	local -a _args_

	set +o nounset
	eval "$(docopt "$@")"
	set -o nounset

	for project in ./*/; do
		if [[ -f "$project/Makefile" || -f "$project/makefile" ]]; then
			make -C "$project" "${_args_[@]}" || exitCode=$?
		fi
	done

	exit "$exitCode"
}

main "$@"
