#!/usr/bin/env bash
set -o errtrace -o nounset -o pipefail

source potpourri.shlib.panic.__err_exit_trap__.bash
source potpourri.shlib.console.info.bash
source potpourri.shlib.assert.is_user.bash
source potpourri.shlib.assert.program_exist.bash
source potpourri.gitlib.globalvar.bash
source potpourri.gitlib.cd_gitroot.bash

# shellcheck disable=SC2034
declare -r DOCOPT_PROGRAM_VERSION="$VERSION
Release date: $RELEASE_DATE"
# shellcheck disable=SC2034
declare -r DOC='Usage:
  git-annex-force-gc
  git-annex-force-gc --version
  git-annex-force-gc -h | --help

Options:
  --version  Show version.
  -h --help  Show this screen.

Author: Nikita Belyakov "Potpourri"
License: MIT
Repo: https://github.com/Potpourri/Hyperborea/tree/master/git-scripts'

main() {
	local unusedCount

	set +o nounset
	eval "$(docopt "$@")"
	set -o nounset

	shlib.assert.is_user
	shlib.assert.program_exist git-annex
	gitlib.cd_gitroot
	if [[ ! -d .git/annex ]]; then
		shlib.panic msg="This script must be run in git-annex repo!"
	fi

	du -sh .git/annex
	echo

	unusedCount=$(git annex unused | wc -l)
	if ((unusedCount <= 1)); then
		shlib.console.info "Not found unused files."
		exit 0
	fi

	git annex dropunused --force all
	echo

	du -sh .git/annex
}

main "$@"
