#!/usr/bin/env bash
set -o errtrace -o nounset -o pipefail

# jscpd:ignore-start
source potpourri.shlib.panic.__err_exit_trap__.bash
source potpourri.shlib.assert.is_user.bash
source potpourri.shlib.assert.program_exist.bash
source potpourri.shlib.assert.file_exist.bash
source potpourri.medialib.globalvar.bash
# jscpd:ignore-end

# shellcheck disable=SC2034
declare -r DOCOPT_PROGRAM_VERSION="$VERSION
Release date: $RELEASE_DATE"
# shellcheck disable=SC2034
declare -r DOC='Usage:
  m4a-to-mp3 <src_m4a> <dest_mp3>
  m4a-to-mp3 --version
  m4a-to-mp3 -h | --help

Options:
  --version  Show version.
  -h --help  Show this screen.

Author: Nikita Belyakov "Potpourri"
License: MIT
Repo: https://github.com/Potpourri/Hyperborea/tree/master/media-scripts'

main() {
	local _src_m4a_ _dest_mp3_

	set +o nounset
	eval "$(docopt "$@")"
	set -o nounset

	shlib.assert.is_user
	shlib.assert.program_exist ffmpeg
	shlib.assert.file_exist "$_src_m4a_"

	ffmpeg -i "$_src_m4a_" -acodec libmp3lame "$_dest_mp3_"
}

main "$@"
