LIB_MODULES := src/lib/potpourri.medialib.globalvar.bash
BIN_MODULES := m4a-to-mp3 \
	merge-video-and-audio \
	pic-is-portrait-fullhd \
	pic-to-portrait-fullhd
SHELLCHECK_IGNORE := src/lib/potpourri.medialib.globalvar.bash
NO_TEST := 1

include ../tools/cfg/hyperborea.mk
