image: registry.gitlab.com/potpourri1/hyperborea

stages:
  - commit-lint
  - style-lint
  - test
  - static-analysis

commit-lint:
  stage: commit-lint
  interruptible: true
  script:
    - git fetch origin master:master --depth 50
    - >
      nix-shell --command '
        commit-lint &&
        makeall clean build &&
        bashfnx potpourri.gitlib.assert_all_committed'

style-lint:
  stage: style-lint
  interruptible: true
  script: nix-shell --run style-lint

test:
  stage: test
  interruptible: true
  script: nix-shell --command 'makeall test'

static-analysis:
  stage: static-analysis
  interruptible: true
  script: nix-shell --run static-analysis
