image: registry.gitlab.com/potpourri1/hyperborea

stages:
  - commit-lint
  - code-lint-or-test

commit-lint:
  stage: commit-lint
  interruptible: true
  script:
    - git fetch origin master:master --depth 50
    - commit-lint
    - makeall clean build
    - bashfnx potpourri.gitlib.assert_all_committed
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'

style-lint:
  stage: code-lint-or-test
  interruptible: true
  script: style-lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "*/src/**/*"
      - "*/makefile"
      - tools/cfg/hyperborea.mk
      - tools/style-lint
      - tools/cfg/cspell.json
    - if: '$CI_PIPELINE_SOURCE == "web"'

test:
  stage: code-lint-or-test
  interruptible: true
  script: makeall test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "*/src/**/*"
      - "*/test/**/*"
      - "*/makefile"
      - tools/cfg/hyperborea.mk
    - if: '$CI_PIPELINE_SOURCE == "web"'

static-analysis:
  stage: code-lint-or-test
  interruptible: true
  script: static-analysis
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "*/src/**/*"
      - "*/makefile"
      - tools/cfg/hyperborea.mk
      - tools/static-analysis
      - .shellcheckrc
      - tools/cfg/jscpd.json
    - if: '$CI_PIPELINE_SOURCE == "web"'
