LIB_MODULES := src/lib/potpourri.gitlib.globalvar.bash \
	src/lib/potpourri.gitlib.cd_gitroot.bash \
	src/lib/potpourri.gitlib.git_no_sign.bash
BIN_MODULES := git-force-gc \
	git-annex-force-gc
SHELLCHECK_IGNORE := src/lib/potpourri.gitlib.globalvar.bash
NO_TEST := 1

include ../tools/cfg/hyperborea.mk
