#!/usr/bin/env bash
set -o errtrace -o nounset -o pipefail

source potpourri.shlib.panic.__err_exit_trap__.bash
source potpourri.shlib.panic.bash
source potpourri.shlib.console.success.bash

if [[ -n $(git status --porcelain) ]]; then
	git status -s
	shlib.panic msg="Hyperborea has uncommitted builds!"
else
	shlib.console.success "All packages builded and committed."
fi
