#!/usr/bin/env bash
set -o errtrace -o nounset -o pipefail

source potpourri.shlib.panic.__err_exit_trap__.bash

declare -a PROJECTS=(
	bash-bundler
	apcselftest
	dotfiles-scripts
	git-scripts
	media-scripts
	nix-shell2docker
	shlib
	update-pinned-nixpkgs
)

main() {
	local -i exitCode=0
	local project

	for project in "${PROJECTS[@]}"; do
		make -C "$project" "$@" || exitCode=$?
	done

	exit "$exitCode"
}

main "$@"
