#!/usr/bin/env bash
set -o errtrace -o nounset -o pipefail

source potpourri.shlib.panic.__err_exit_trap__.bash

main() {
	local -i exitCode=0
	local project

	for project in ./*/; do
		if [[ -f "$project/Makefile" || -f "$project/makefile" ]]; then
			make -C "$project" "$@" || exitCode=$?
		fi
	done

	exit "$exitCode"
}

main "$@"
