#!/usr/bin/env bash
set -o errtrace -o nounset -o pipefail

source potpourri.shlib.panic.__err_exit_trap__.bash
source potpourri.shlib.console.info.bash
source potpourri.shlib.console.success.bash

main() {
	local -i exitCode=0

	cd "${PROJECT_ROOT:?}"

	shlib.console.info "Shfmt and cSpell stage."
	makeall style-lint || exitCode=$?
	if [[ $exitCode == 0 ]]; then
		shlib.console.success "Shfmt and cSpell stage complete."
	fi

	shlib.console.info "cSpell check 'tools' and docs."
	find tools -maxdepth 1 -type f -exec \
		cspell --config tools/cfg/cspell.json README.org {} + || exitCode=$?
	if [[ $exitCode == 0 ]]; then
		shlib.console.success "cSpell check 'tools' and docs complete."
	fi

	exit "$exitCode"
}

main
